In [1]:
import pandas as pd
import os
from datetime import datetime, timedelta

directory = 'C:/Users/tuan-/Downloads/1 Lobster Thesis/Data/SPY2023/'

# Konverter tid
def convert_to_datetime(seconds, base_date):
    base_time = datetime.strptime(base_date, '%Y-%m-%d')
    return base_time + timedelta(seconds=seconds)

# monthly data
monthly_data = []

year = 2023

 # Loop monthly
for month in range(1, 13): 
    monthly_files = []
    
    for filename in os.listdir(directory):
        if f'{year}-{month:02}' in filename and 'message' in filename:  # Match filer monthly and year
            message_file = os.path.join(directory, filename)
            orderbook_file = message_file.replace('message', 'orderbook')  # Match orderbook fil
            
            # Gå i stå, slet tomme filer
            if os.path.getsize(message_file) == 0 or os.path.getsize(orderbook_file) == 0:
                print(f"Skipping empty file: {message_file} or {orderbook_file}")
                continue  

            try:
        
                message_df = pd.read_csv(message_file, encoding='utf-8', low_memory=False)
                orderbook_df = pd.read_csv(orderbook_file, encoding='utf-8', low_memory=False)
            except Exception as e:
                print(f"Error loading file {filename}: {e}")
                continue  # Skip this file if there's an error

            # Dropper col 7
            message_df = message_df.iloc[:, :-1]  # Drop last column
            message_df.columns = ['Time (sec)', 'Event Type', 'Order ID', 'Size', 'Price', 'Direction']
            orderbook_df.columns = ['Ask Price 1', 'Ask Size 1', 'Bid Price 1', 'Bid Size 1', 
                                    'Ask Price 2', 'Ask Size 2', 'Bid Price 2', 'Bid Size 2']

            # Start dag SPY_2023-01-03
            base_date = filename.split('_')[1]
            
            
            message_df['Time (sec)'] = message_df['Time (sec)'].apply(lambda x: convert_to_datetime(x, base_date))

            # Merge message and orderbook 
            combined_df = pd.merge(orderbook_df, message_df, left_index=True, right_index=True, how='left')

            # Slet NAN
            combined_df.dropna(inplace=True)

            # Set 'Time (sec)' as index for 1 sec
            combined_df.set_index('Time (sec)', inplace=True)

            # Sampler data 1 sec interval første obs hvert sec
            resampled_df = combined_df.resample('1S').first()

            
            monthly_files.append(resampled_df)
    
    # Concatenate all daily files for the month
    if monthly_files:
        monthly_data_df = pd.concat(monthly_files)
        monthly_data.append(monthly_data_df)
        
        
        monthly_data_df.to_csv(f'processed_{year}_{month:02}.csv', index=False)


final_df = pd.concat(monthly_data)


final_df.to_csv(f'combined_SPY_{year}_cleaned.csv', index=False)

print(final_df.head())

                     Ask Price 1  Ask Size 1  Bid Price 1  Bid Size 1  \
Time (sec)
2023-01-03 09:30:00    3844100.0       100.0    3843400.0       300.0
2023-01-03 09:30:01    3844200.0       700.0    3844000.0       200.0
2023-01-03 09:30:02    3844100.0       400.0    3843400.0       197.0
2023-01-03 09:30:03    3843800.0       118.0    3843400.0       200.0
2023-01-03 09:30:04    3843900.0       800.0    3843400.0       300.0

                     Ask Price 2  Ask Size 2  Bid Price 2  Bid Size 2  \
Time (sec)
2023-01-03 09:30:00    3844200.0       600.0    3843300.0       600.0
2023-01-03 09:30:01    3844300.0       800.0    3843900.0       300.0
2023-01-03 09:30:02    3844200.0       700.0    3843300.0       820.0
2023-01-03 09:30:03    3843900.0       700.0    3843300.0       420.0
2023-01-03 09:30:04    3844000.0       700.0    3843300.0       100.0

                     Event Type    Order ID   Size      Price  Direction
Time (sec)
2023-01-03 09:30:00         1.0  39946724.0  100.0  3843400.0        1.0
2023-01-03 09:30:01         1.0  40482608.0  200.0  3844000.0        1.0
2023-01-03 09:30:02         4.0  40787052.0  200.0  3844100.0       -1.0
2023-01-03 09:30:03         3.0  41131364.0  500.0  3843300.0        1.0
2023-01-03 09:30:04         3.0  41361344.0  500.0  3843300.0        1.0

In [17]:
print(final_df.tail())

                     Ask Price 1  Ask Size 1  Bid Price 1  Bid Size 1  \
Time (sec)
2023-12-29 15:59:55    4754400.0       900.0    4754300.0       100.0
2023-12-29 15:59:56    4754200.0       800.0    4754100.0       300.0
2023-12-29 15:59:57    4753100.0      1587.0    4753000.0       800.0
2023-12-29 15:59:58    4753100.0      1200.0    4752900.0       600.0
2023-12-29 15:59:59    4753100.0       600.0    4752900.0       600.0

                     Ask Price 2  Ask Size 2  Bid Price 2  Bid Size 2  \
Time (sec)
2023-12-29 15:59:55    4754500.0       800.0    4754200.0      1670.0
2023-12-29 15:59:56    4754300.0       800.0    4754000.0       500.0
2023-12-29 15:59:57    4753200.0      1200.0    4752900.0      1300.0
2023-12-29 15:59:58    4753200.0      2100.0    4752800.0      1200.0
2023-12-29 15:59:59    4753200.0      2000.0    4752800.0      1300.0

                     Event Type     Order ID   Size      Price  Direction  \
Time (sec)
2023-12-29 15:59:55         3.0  876117912.0  400.0  4754400.0       -1.0
2023-12-29 15:59:56         3.0  876365300.0  300.0  4754200.0       -1.0
2023-12-29 15:59:57         3.0  876541100.0  100.0  4753000.0        1.0
2023-12-29 15:59:58         4.0  876747648.0  200.0  4753000.0        1.0
2023-12-29 15:59:59         4.0  876923912.0  200.0  4753100.0       -1.0

                           Date
Time (sec)
2023-12-29 15:59:55  2023-12-29
2023-12-29 15:59:56  2023-12-29
2023-12-29 15:59:57  2023-12-29
2023-12-29 15:59:58  2023-12-29
2023-12-29 15:59:59  2023-12-29

In [3]:
# Observations (rows) in the final combined DataFrame for the year
total_observations_final = len(final_df)

print(f"Total observations in the final combined DataFrame: {total_observations_final}")

Total observations in the final combined DataFrame: 5740269

In [4]:
final_df.head()

,Ask Price 1,Ask Size 1,Bid Price 1,Bid Size 1,Ask Price 2,Ask Size 2,Bid Price 2,Bid Size 2,Event Type,Order ID,Size,Price,Direction
Time (sec),,,,,,,,,,,,,
2023-01-03 09:30:00,3844100.0,100.0,3843400.0,300.0,3844200.0,600.0,3843300.0,600.0,1.0,39946724.0,100.0,3843400.0,1.0
2023-01-03 09:30:01,3844200.0,700.0,3844000.0,200.0,3844300.0,800.0,3843900.0,300.0,1.0,40482608.0,200.0,3844000.0,1.0
2023-01-03 09:30:02,3844100.0,400.0,3843400.0,197.0,3844200.0,700.0,3843300.0,820.0,4.0,40787052.0,200.0,3844100.0,-1.0
2023-01-03 09:30:03,3843800.0,118.0,3843400.0,200.0,3843900.0,700.0,3843300.0,420.0,3.0,41131364.0,500.0,3843300.0,1.0
2023-01-03 09:30:04,3843900.0,800.0,3843400.0,300.0,3844000.0,700.0,3843300.0,100.0,3.0,41361344.0,500.0,3843300.0,1.0

In [5]:
final_df.tail()

,Ask Price 1,Ask Size 1,Bid Price 1,Bid Size 1,Ask Price 2,Ask Size 2,Bid Price 2,Bid Size 2,Event Type,Order ID,Size,Price,Direction
Time (sec),,,,,,,,,,,,,
2023-12-29 15:59:55,4754400.0,900.0,4754300.0,100.0,4754500.0,800.0,4754200.0,1670.0,3.0,876117912.0,400.0,4754400.0,-1.0
2023-12-29 15:59:56,4754200.0,800.0,4754100.0,300.0,4754300.0,800.0,4754000.0,500.0,3.0,876365300.0,300.0,4754200.0,-1.0
2023-12-29 15:59:57,4753100.0,1587.0,4753000.0,800.0,4753200.0,1200.0,4752900.0,1300.0,3.0,876541100.0,100.0,4753000.0,1.0
2023-12-29 15:59:58,4753100.0,1200.0,4752900.0,600.0,4753200.0,2100.0,4752800.0,1200.0,4.0,876747648.0,200.0,4753000.0,1.0
2023-12-29 15:59:59,4753100.0,600.0,4752900.0,600.0,4753200.0,2000.0,4752800.0,1300.0,4.0,876923912.0,200.0,4753100.0,-1.0

In [6]:
# # Save 
# final_df.to_csv('final_combined_2023.csv', index=True)  # Keep the index to retain 'Time (sec)'

final_df.to_csv('final_combined_2023_with_time.csv', index=True)

In [18]:
# Count unique days
final_df['Date'] = final_df.index.date

# Count the number of unique trading days
unique_trading_days = final_df['Date'].nunique()

print(f"Number of unique trading days: {unique_trading_days}")

# Count the number of observations (rows) in the resampled DataFrame
num_observations = len(resampled_df)

# 
print(f'Total number of observations: {num_observations}')

Number of unique trading days: 249
Total number of observations: 23400

In [8]:
# Load the data from 'final_combined_2023_with_time.csv'
final_combined_2023_with_time = pd.read_csv('final_combined_2023_with_time.csv')


final_combined_2023_with_time['Time (sec)'] = pd.to_datetime(final_combined_2023_with_time['Time (sec)'])

# Group trading days
grouped = final_combined_2023_with_time.groupby(final_combined_2023_with_time['Time (sec)'].dt.date)

# Sampler liste
resampled_5min_list = []

# Iterate through each group each day
for date, group in grouped:
    # Filtrer data for trading hours (9:30 AM to 4:00 PM)
    group_trading_hours = group[
        (group['Time (sec)'].dt.time >= pd.to_datetime('09:30:00').time()) &
        (group['Time (sec)'].dt.time <= pd.to_datetime('16:00:00').time())
    ]
    
    # Resample for 5-minute intervals 
    resampled_day = group_trading_hours.resample('5T', on='Time (sec)').agg({
        'Ask Price 1': ['first', 'max', 'min', 'last'],
        'Bid Price 1': ['first', 'max', 'min', 'last'],
        'Ask Price 2': ['first', 'max', 'min', 'last'],
        'Bid Price 2': ['first', 'max', 'min', 'last'],
        'Ask Size 1': ['sum', 'mean'],
        'Bid Size 1': ['sum', 'mean'],
        'Ask Size 2': ['sum', 'mean'],
        'Bid Size 2': ['sum', 'mean'],
        'Price': ['first', 'max', 'min', 'last'],
        'Direction': 'mean'
    })
    
   
    resampled_day.columns = ['_'.join(col).strip() for col in resampled_day.columns.values]
    
    # Append the resampled data dag
    resampled_5min_list.append(resampled_day)

# Concatenate all, DataFrame
resampled_5min_final_df = pd.concat(resampled_5min_list)

# Reset index 'Time (sec)' 
resampled_5min_final_df.reset_index(inplace=True)

In [9]:
print(resampled_5min_final_df.head(10))

           Time (sec)  Ask Price 1_first  Ask Price 1_max  Ask Price 1_min  \
0 2023-01-03 09:30:00          3844100.0        3851300.0        3836200.0
1 2023-01-03 09:35:00          3845400.0        3854600.0        3843500.0
2 2023-01-03 09:40:00          3854100.0        3864000.0        3852100.0
3 2023-01-03 09:45:00          3852900.0        3853700.0        3830600.0
4 2023-01-03 09:50:00          3835100.0        3839600.0        3825500.0
5 2023-01-03 09:55:00          3828300.0        3831000.0        3816900.0
6 2023-01-03 10:00:00          3817300.0        3825600.0        3817100.0
7 2023-01-03 10:05:00          3821400.0        3823700.0        3818000.0
8 2023-01-03 10:10:00          3819900.0        3820500.0        3809500.0
9 2023-01-03 10:15:00          3811800.0        3813700.0        3802400.0

   Ask Price 1_last  Bid Price 1_first  Bid Price 1_max  Bid Price 1_min  \
0         3845000.0          3843400.0        3851100.0        3836000.0
1         3853400.0          3844900.0        3854300.0        3843200.0
2         3852600.0          3853700.0        3863600.0        3851600.0
3         3835200.0          3852600.0        3853300.0        3830400.0
4         3828300.0          3834900.0        3839300.0        3825100.0
5         3817200.0          3827900.0        3830800.0        3816600.0
6         3821300.0          3817000.0        3825500.0        3816900.0
7         3820400.0          3821000.0        3823500.0        3817700.0
8         3811500.0          3819500.0        3820100.0        3809300.0
9         3802700.0          3811600.0        3813500.0        3802200.0

   Bid Price 1_last  Ask Price 2_first  ...  Bid Size 1_mean  Ask Size 2_sum  \
0         3844600.0          3844200.0  ...       249.576667        128072.0
1         3853100.0          3845500.0  ...       303.996667        156271.0
2         3852200.0          3854200.0  ...       447.693333         94597.0
3         3835100.0          3853200.0  ...       399.713333        142322.0
4         3827900.0          3835200.0  ...       297.323333        143619.0
5         3816700.0          3828400.0  ...       353.916667        157338.0
6         3820900.0          3817400.0  ...       235.756667         97452.0
7         3820100.0          3821500.0  ...       268.866667        109478.0
8         3811200.0          3820000.0  ...       329.786667        166385.0
9         3802500.0          3811900.0  ...       206.876667         79044.0

   Ask Size 2_mean  Bid Size 2_sum  Bid Size 2_mean  Price_first  Price_max  \
0       426.906667        123276.0       410.920000    3843400.0  3850900.0
1       520.903333        167164.0       557.213333    3845400.0  3854600.0
2       315.323333        119734.0       399.113333    3854100.0  3864000.0
3       474.406667        146912.0       489.706667    3852600.0  3853600.0
4       478.730000        146215.0       487.383333    3835100.0  3839300.0
5       524.460000        141644.0       472.146667    3827900.0  3831000.0
6       324.840000        108534.0       361.780000    3817000.0  3825500.0
7       364.926667        121728.0       405.760000    3821400.0  3823700.0
8       554.616667        171357.0       571.190000    3819900.0  3820300.0
9       263.480000        105404.0       351.346667    3811800.0  3813500.0

   Price_min  Price_last  Direction_mean
0  3836200.0   3844600.0        0.073333
1  3843500.0   3853100.0        0.026667
2  3851500.0   3852200.0        0.033333
3  3830500.0   3835200.0       -0.153333
4  3825400.0   3828300.0       -0.080000
5  3816800.0   3817200.0       -0.060000
6  3817000.0   3820900.0       -0.086667
7  3817600.0   3819900.0       -0.060000
8  3809400.0   3811500.0       -0.100000
9  3802200.0   3802500.0        0.106667

[10 rows x 30 columns]

In [10]:
# Save
resampled_5min_final_df.to_csv('resampled_5min_final_2023_corrected.csv', index=False)

In [11]:
# Count observations for each day in 5-minute interval
resampled_5min_final_df['Date'] = resampled_5min_final_df['Time (sec)'].dt.date

# Count the number of rows for each day
observations_per_day = resampled_5min_final_df.groupby('Date').size()


print(observations_per_day)

Date
2023-01-03    78
2023-01-04    78
2023-01-05    78
2023-01-06    78
2023-01-09    78
              ..
2023-12-22    78
2023-12-26    78
2023-12-27    78
2023-12-28    78
2023-12-29    78
Length: 249, dtype: int64

In [12]:
print(resampled_5min_final_df.head(10))

# Save igen
resampled_5min_final_df.to_csv('resampled_5min_final_2023_corrected.csv', index=False)

           Time (sec)  Ask Price 1_first  Ask Price 1_max  Ask Price 1_min  \
0 2023-01-03 09:30:00          3844100.0        3851300.0        3836200.0
1 2023-01-03 09:35:00          3845400.0        3854600.0        3843500.0
2 2023-01-03 09:40:00          3854100.0        3864000.0        3852100.0
3 2023-01-03 09:45:00          3852900.0        3853700.0        3830600.0
4 2023-01-03 09:50:00          3835100.0        3839600.0        3825500.0
5 2023-01-03 09:55:00          3828300.0        3831000.0        3816900.0
6 2023-01-03 10:00:00          3817300.0        3825600.0        3817100.0
7 2023-01-03 10:05:00          3821400.0        3823700.0        3818000.0
8 2023-01-03 10:10:00          3819900.0        3820500.0        3809500.0
9 2023-01-03 10:15:00          3811800.0        3813700.0        3802400.0

   Ask Price 1_last  Bid Price 1_first  Bid Price 1_max  Bid Price 1_min  \
0         3845000.0          3843400.0        3851100.0        3836000.0
1         3853400.0          3844900.0        3854300.0        3843200.0
2         3852600.0          3853700.0        3863600.0        3851600.0
3         3835200.0          3852600.0        3853300.0        3830400.0
4         3828300.0          3834900.0        3839300.0        3825100.0
5         3817200.0          3827900.0        3830800.0        3816600.0
6         3821300.0          3817000.0        3825500.0        3816900.0
7         3820400.0          3821000.0        3823500.0        3817700.0
8         3811500.0          3819500.0        3820100.0        3809300.0
9         3802700.0          3811600.0        3813500.0        3802200.0

   Bid Price 1_last  Ask Price 2_first  ...  Ask Size 2_sum  Ask Size 2_mean  \
0         3844600.0          3844200.0  ...        128072.0       426.906667
1         3853100.0          3845500.0  ...        156271.0       520.903333
2         3852200.0          3854200.0  ...         94597.0       315.323333
3         3835100.0          3853200.0  ...        142322.0       474.406667
4         3827900.0          3835200.0  ...        143619.0       478.730000
5         3816700.0          3828400.0  ...        157338.0       524.460000
6         3820900.0          3817400.0  ...         97452.0       324.840000
7         3820100.0          3821500.0  ...        109478.0       364.926667
8         3811200.0          3820000.0  ...        166385.0       554.616667
9         3802500.0          3811900.0  ...         79044.0       263.480000

   Bid Size 2_sum  Bid Size 2_mean  Price_first  Price_max  Price_min  \
0        123276.0       410.920000    3843400.0  3850900.0  3836200.0
1        167164.0       557.213333    3845400.0  3854600.0  3843500.0
2        119734.0       399.113333    3854100.0  3864000.0  3851500.0
3        146912.0       489.706667    3852600.0  3853600.0  3830500.0
4        146215.0       487.383333    3835100.0  3839300.0  3825400.0
5        141644.0       472.146667    3827900.0  3831000.0  3816800.0
6        108534.0       361.780000    3817000.0  3825500.0  3817000.0
7        121728.0       405.760000    3821400.0  3823700.0  3817600.0
8        171357.0       571.190000    3819900.0  3820300.0  3809400.0
9        105404.0       351.346667    3811800.0  3813500.0  3802200.0

   Price_last  Direction_mean        Date
0   3844600.0        0.073333  2023-01-03
1   3853100.0        0.026667  2023-01-03
2   3852200.0        0.033333  2023-01-03
3   3835200.0       -0.153333  2023-01-03
4   3828300.0       -0.080000  2023-01-03
5   3817200.0       -0.060000  2023-01-03
6   3820900.0       -0.086667  2023-01-03
7   3819900.0       -0.060000  2023-01-03
8   3811500.0       -0.100000  2023-01-03
9   3802500.0        0.106667  2023-01-03

[10 rows x 31 columns]

In [13]:
from IPython.display import display, HTML

# Display as an HTML tabel
html_table = resampled_5min_final_df.head(10).to_html(index=False)
display(HTML(html_table))

# Gem denne
resampled_5min_final_df.to_csv('resampled_5min_final_2023_corrected.csv', index=False)

In [14]:
from IPython.display import display, HTML

# Display as an HTML tabel
html_table = resampled_5min_final_df.tail(10).to_html(index=False)
display(HTML(html_table))

# Gem denne
resampled_5min_final_df.to_csv('resampled_5min_final_2023_corrected.csv', index=False)